"""
Phase 2 Acceptance Tests — RBAC via org_memberships

Tests the following acceptance criteria:

  - Authorization comes from org_memberships, not token org_id alone.
  - Client executive (role=executive) CAN create attestations → 201.
  - MSP technician (role=msp_technician) CANNOT create attestations → 403.
  - Permission matrix: every role × every protected endpoint.
  - Findings state machine: full lifecycle happy path.
  - Self-approval prohibition: same user submit + approve → 409.
  - Members API: invite, list, change role, revoke.

Security invariants preserved:
  - Actor fields always come from JWT, never from body.
  - Server sets all timestamps.
  - Deny by default: no membership → 403.
  - Cross-tenant access returns 404.
"""

import pytest
from fastapi.testclient import TestClient

# conftest sets ENV=test and auth vars before any app import
from backend.auth.jwt import sign_dev_token
from backend.repositories.org_membership_repo import OrgMembership, org_membership_repo
from backend.repositories.finding_repo import finding_repo
from backend.securityos_main import app

# ── Test IDs ──────────────────────────────────────────────────────────────────

ORG_P2 = "org-phase2-test-001"
MSP_ID_P2 = "msp-phase2-test"

# User IDs for each role
UID_ADMIN  = "user-p2-admin"
UID_EXEC   = "user-p2-exec"
UID_ENG    = "user-p2-engineer"
UID_TECH   = "user-p2-msp-tech"   # MSP technician
UID_AUDIT  = "user-p2-auditor"
UID_NOBODY = "user-p2-nobody"     # valid JWT but no membership in ORG_P2


def _tok(
    *,
    user_id: str,
    org_id: str = ORG_P2,
    msp_id: str | None = None,
    email: str | None = None,
    name: str | None = None,
) -> str:
    claims: dict = {
        "sub": user_id,
        "email": email or f"{user_id}@example.com",
        "name": name or user_id,
        "org_id": org_id,
    }
    if msp_id is not None:
        claims["msp_id"] = msp_id
    return sign_dev_token(claims, expires_in=3600)


# Build tokens at module level (key is already generated by conftest)
ADMIN_TOKEN  = _tok(user_id=UID_ADMIN)
EXEC_TOKEN   = _tok(user_id=UID_EXEC)
ENG_TOKEN    = _tok(user_id=UID_ENG)
TECH_TOKEN   = _tok(user_id=UID_TECH, org_id="org-msp-internal-p2", msp_id=MSP_ID_P2)
AUDIT_TOKEN  = _tok(user_id=UID_AUDIT)
NOBODY_TOKEN = _tok(user_id=UID_NOBODY, org_id="org-p2-other")


@pytest.fixture(scope="module")
def client():
    """Module-scoped client; memberships and findings are set up once."""
    # Register MSP so the technician can see ORG_P2 via manages_org()
    from backend.repositories.msp_org_repo import msp_org_repo
    msp_org_repo.add_org(MSP_ID_P2, ORG_P2)

    # Seed org_membership_repo for ORG_P2
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc).isoformat()
    for uid, role in [
        (UID_ADMIN,  "admin"),
        (UID_EXEC,   "executive"),
        (UID_ENG,    "engineer"),
        (UID_TECH,   "msp_technician"),
        (UID_AUDIT,  "auditor"),
    ]:
        org_membership_repo.add(OrgMembership(
            user_id=uid,
            org_id=ORG_P2,
            role=role,
            granted_by=UID_ADMIN,
            granted_at=now,
        ))

    with TestClient(app, raise_server_exceptions=True) as c:
        yield c

    # Teardown
    org_membership_repo._clear()
    finding_repo._clear()
    from backend.repositories.msp_org_repo import msp_org_repo as _msp_repo
    _msp_repo._clear()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _auth(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def _attest_payload() -> dict:
    return {
        "source_name": "CrowdStrike Falcon",
        "source_description": "EDR platform covering endpoint controls.",
        "control_ids": ["CTRL-P2-001"],
        "confirmation_phrase": "ATTEST",
    }


# ── Membership check: no membership → 403 ────────────────────────────────────

def test_no_membership_cannot_attest(client):
    """A valid JWT with no membership in the org must receive 403."""
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(NOBODY_TOKEN),
    )
    # NOBODY_TOKEN has org_id=org-p2-other, so manages_org(ORG_P2) = False → 404
    assert resp.status_code == 404, (
        f"Expected 404 for cross-tenant access, got {resp.status_code}: {resp.text}"
    )


# ── Client executive CAN attest ───────────────────────────────────────────────

def test_client_executive_can_create_attestation(client):
    """
    A user with role=executive in an org can create attestations.
    This is the primary Phase 2 acceptance criterion.
    """
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(EXEC_TOKEN),
    )
    assert resp.status_code == 201, (
        f"Client executive attestation failed: {resp.status_code} — {resp.text}"
    )
    body = resp.json()
    attest = body["attestation"]
    # Server must set actor from JWT, never from body
    assert attest["created_by_user_id"] == UID_EXEC
    assert attest["created_by_email"] == f"{UID_EXEC}@example.com"


# ── MSP technician CANNOT attest ─────────────────────────────────────────────

def test_msp_technician_cannot_create_attestation(client):
    """
    A user with role=msp_technician does NOT have attestation.create.
    They must receive 403 even though they can see the org (manages_org = True).
    """
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(TECH_TOKEN),
    )
    assert resp.status_code == 403, (
        f"MSP technician should be denied attestation.create, got {resp.status_code}: {resp.text}"
    )
    assert "attestation.create" in resp.json().get("detail", "").lower()


# ── Admin CAN attest ──────────────────────────────────────────────────────────

def test_admin_can_create_attestation(client):
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(ADMIN_TOKEN),
    )
    assert resp.status_code == 201, f"{resp.status_code}: {resp.text}"


# ── Engineer CANNOT attest ────────────────────────────────────────────────────

def test_engineer_cannot_create_attestation(client):
    """Engineers can remediate findings but not create attestations."""
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(ENG_TOKEN),
    )
    assert resp.status_code == 403, f"Engineer should not attest: {resp.status_code}: {resp.text}"


# ── Auditor CANNOT attest ─────────────────────────────────────────────────────

def test_auditor_cannot_create_attestation(client):
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/attestations",
        json=_attest_payload(),
        headers=_auth(AUDIT_TOKEN),
    )
    assert resp.status_code == 403, f"Auditor should not attest: {resp.status_code}: {resp.text}"


# ── Finding lifecycle — happy path ────────────────────────────────────────────

def test_finding_full_lifecycle(client):
    """
    Full finding lifecycle:
      engineer creates → engineer assigns → engineer starts → engineer submits
      → executive approves → closed
    """
    # 1. Create finding (engineer)
    create_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        json={
            "title": "Missing MFA on admin accounts",
            "description": "Admin accounts do not enforce MFA.",
            "severity": "high",
            "control_ids": ["CTRL-P2-IAM-001"],
        },
        headers=_auth(ENG_TOKEN),
    )
    assert create_resp.status_code == 201, f"Create finding: {create_resp.text}"
    finding_id = create_resp.json()["finding"]["finding_id"]
    assert create_resp.json()["finding"]["state"] == "open"

    # 2. Assign (engineer assigns to themselves)
    assign_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "assign", "assigned_to_user_id": UID_ENG},
        headers=_auth(ENG_TOKEN),
    )
    assert assign_resp.status_code == 200, f"Assign: {assign_resp.text}"
    assert assign_resp.json()["finding"]["state"] == "assigned"

    # 3. Start (engineer)
    start_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "start"},
        headers=_auth(ENG_TOKEN),
    )
    assert start_resp.status_code == 200, f"Start: {start_resp.text}"
    assert start_resp.json()["finding"]["state"] == "in_progress"

    # 4. Submit for review (engineer)
    submit_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "submit", "note": "MFA enforced via Entra Conditional Access."},
        headers=_auth(ENG_TOKEN),
    )
    assert submit_resp.status_code == 200, f"Submit: {submit_resp.text}"
    assert submit_resp.json()["finding"]["state"] == "submitted_for_review"

    # 5. Approve (executive — NOT the same as the engineer who submitted)
    approve_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "approve", "note": "Verified MFA policy applied."},
        headers=_auth(EXEC_TOKEN),
    )
    assert approve_resp.status_code == 200, f"Approve: {approve_resp.text}"
    assert approve_resp.json()["finding"]["state"] == "closed"


# ── Self-approval prohibition ─────────────────────────────────────────────────

def test_self_approval_prohibited(client):
    """
    The same user who submitted a finding for review cannot approve/close it.
    Attempt → 409 Conflict.
    """
    # Create a finding
    create_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        json={
            "title": "Self-approval test finding",
            "description": "Should not be self-approachable.",
            "severity": "medium",
            "control_ids": [],
        },
        headers=_auth(ADMIN_TOKEN),  # admin creates
    )
    assert create_resp.status_code == 201
    finding_id = create_resp.json()["finding"]["finding_id"]

    # Admin assigns
    client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "assign", "assigned_to_user_id": UID_ADMIN},
        headers=_auth(ADMIN_TOKEN),
    )

    # Admin starts
    client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "start"},
        headers=_auth(ADMIN_TOKEN),
    )

    # Admin submits (the same user who will try to approve)
    submit_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "submit", "note": "I fixed it."},
        headers=_auth(ADMIN_TOKEN),
    )
    assert submit_resp.status_code == 200

    # Same admin tries to approve — must be rejected
    approve_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "approve"},
        headers=_auth(ADMIN_TOKEN),
    )
    assert approve_resp.status_code == 409, (
        f"Expected 409 for self-approval, got {approve_resp.status_code}: {approve_resp.text}"
    )
    assert "self-approval" in approve_resp.json().get("detail", "").lower()


# ── Engineer cannot approve ───────────────────────────────────────────────────

def test_engineer_cannot_approve_finding(client):
    """Engineers lack finding.approve_close; approval attempt → 403."""
    create_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        json={
            "title": "Engineer approve test",
            "description": "Test permission boundary.",
            "severity": "low",
            "control_ids": [],
        },
        headers=_auth(ENG_TOKEN),
    )
    assert create_resp.status_code == 201
    finding_id = create_resp.json()["finding"]["finding_id"]

    # Advance to submitted_for_review state via engineer path
    for action, body in [
        ("assign", {"action": "assign", "assigned_to_user_id": UID_ENG}),
        ("start", {"action": "start"}),
        ("submit", {"action": "submit"}),
    ]:
        r = client.post(
            f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
            json=body,
            headers=_auth(ENG_TOKEN),
        )
        assert r.status_code == 200, f"Step {action}: {r.text}"

    # Engineer tries to approve — should be 403
    approve_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings/{finding_id}/transition",
        json={"action": "approve"},
        headers=_auth(ENG_TOKEN),
    )
    assert approve_resp.status_code == 403, (
        f"Expected 403 for engineer approve, got {approve_resp.status_code}: {approve_resp.text}"
    )


# ── Auditor can view findings but not create them ─────────────────────────────

def test_auditor_can_view_findings(client):
    resp = client.get(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        headers=_auth(AUDIT_TOKEN),
    )
    assert resp.status_code == 200, f"{resp.status_code}: {resp.text}"


def test_auditor_cannot_create_finding(client):
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        json={
            "title": "Auditor should not create",
            "description": "...",
            "severity": "info",
            "control_ids": [],
        },
        headers=_auth(AUDIT_TOKEN),
    )
    assert resp.status_code == 403, f"Auditor should not create findings: {resp.status_code}"


# ── Members API ───────────────────────────────────────────────────────────────

def test_get_me_returns_identity_and_memberships(client):
    resp = client.get("/api/v1/securityos/me", headers=_auth(EXEC_TOKEN))
    assert resp.status_code == 200
    body = resp.json()
    assert body["user_id"] == UID_EXEC
    assert any(m["role"] == "executive" and m["org_id"] == ORG_P2 for m in body["memberships"])


def test_list_members_requires_org_manage(client):
    """Auditor lacks org.manage; listing members → 403."""
    resp = client.get(
        f"/api/v1/securityos/organizations/{ORG_P2}/members",
        headers=_auth(AUDIT_TOKEN),
    )
    assert resp.status_code == 403, f"Auditor list members: {resp.status_code}"


def test_admin_can_list_members(client):
    resp = client.get(
        f"/api/v1/securityos/organizations/{ORG_P2}/members",
        headers=_auth(ADMIN_TOKEN),
    )
    assert resp.status_code == 200
    assert resp.json()["total"] >= 5  # at least the 5 seeded members


def test_invite_and_revoke_member(client):
    """Admin invites a new user, then revokes the membership."""
    new_uid = "user-p2-invite-test"
    invite_resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/members",
        json={"user_id": new_uid, "role": "auditor"},
        headers=_auth(ADMIN_TOKEN),
    )
    assert invite_resp.status_code == 201, f"Invite: {invite_resp.text}"
    assert invite_resp.json()["membership"]["role"] == "auditor"

    # Revoke
    revoke_resp = client.delete(
        f"/api/v1/securityos/organizations/{ORG_P2}/members/{new_uid}",
        headers=_auth(ADMIN_TOKEN),
    )
    assert revoke_resp.status_code == 204, f"Revoke: {revoke_resp.text}"

    # Gone from the list
    list_resp = client.get(
        f"/api/v1/securityos/organizations/{ORG_P2}/members",
        headers=_auth(ADMIN_TOKEN),
    )
    uids_in_org = [m["user_id"] for m in list_resp.json()["members"]]
    assert new_uid not in uids_in_org


def test_change_member_role(client):
    """Admin changes an engineer's role to auditor, then back."""
    patch_resp = client.patch(
        f"/api/v1/securityos/organizations/{ORG_P2}/members/{UID_AUDIT}",
        json={"role": "engineer"},
        headers=_auth(ADMIN_TOKEN),
    )
    assert patch_resp.status_code == 200, f"Role change: {patch_resp.text}"
    assert patch_resp.json()["membership"]["role"] == "engineer"

    # Restore
    client.patch(
        f"/api/v1/securityos/organizations/{ORG_P2}/members/{UID_AUDIT}",
        json={"role": "auditor"},
        headers=_auth(ADMIN_TOKEN),
    )


# ── Invalid body → 422 ────────────────────────────────────────────────────────

def test_finding_create_with_extra_field_returns_422(client):
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/findings",
        json={
            "title": "test",
            "description": "desc",
            "severity": "low",
            "control_ids": [],
            "created_by_user_id": "hacker",  # forbidden extra field
        },
        headers=_auth(ENG_TOKEN),
    )
    assert resp.status_code == 422


def test_member_invite_with_invalid_role_returns_422(client):
    resp = client.post(
        f"/api/v1/securityos/organizations/{ORG_P2}/members",
        json={"user_id": "someuser", "role": "superadmin"},
        headers=_auth(ADMIN_TOKEN),
    )
    assert resp.status_code == 422
