"""
SecurityOS Control Catalog — 25 foundational controls.
Customers see plain language; framework mappings stay under the hood.
"""
from typing import Dict, List, Optional
from enum import Enum


class Category(str, Enum):
    IDENTITY = "identity"
    DEVICES = "devices"
    DATA = "data"
    NETWORK = "network"
    ORGANIZATION = "organization"


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ControlStatus(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    UNKNOWN = "unknown"
    IN_PROGRESS = "in_progress"


class EvidenceType(str, Enum):
    IDENTITY_PROVIDER = "identity_provider"
    ENDPOINT = "endpoint"
    CLOUD_PLATFORM = "cloud_platform"
    BACKUP_PLATFORM = "backup_platform"
    NETWORK = "network"
    POLICY = "policy"


CATEGORY_META = {
    Category.IDENTITY:     {"label": "Identity",        "max_score": 20, "description": "Who has access to your systems and data"},
    Category.DEVICES:      {"label": "Devices",         "max_score": 20, "description": "Security of computers, phones, and hardware"},
    Category.DATA:         {"label": "Data",            "max_score": 20, "description": "Protection and backup of sensitive information"},
    Category.NETWORK:      {"label": "Cloud & Network", "max_score": 20, "description": "Security of your cloud services and network"},
    Category.ORGANIZATION: {"label": "Organization",    "max_score": 20, "description": "Policies, training, and incident readiness"},
}

CONTROLS: List[Dict] = [
    # ── IDENTITY ──────────────────────────────────────────────────────────────
    {
        "id": "CTRL-ID-001",
        "category": Category.IDENTITY,
        "title": "Multi-Factor Authentication (MFA)",
        "short_title": "MFA",
        "description": "Require a second form of verification for all user accounts, especially admin and privileged accounts.",
        "why_it_matters": "MFA blocks over 99% of automated account attacks. A stolen password alone is not enough to access your systems.",
        "how_to_fix": [
            "Sign in to your Microsoft 365 or Google Workspace admin console.",
            "Navigate to Security → Multi-Factor Authentication.",
            "Require MFA for all users, starting with admins.",
            "Notify employees and give them 48 hours to enroll.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-02"], "cis": ["5.2"], "cyber_insurance": True},
        "severity": Severity.CRITICAL,
        "evidence_type": EvidenceType.IDENTITY_PROVIDER,
        "estimated_minutes": 30,
        "weight": 5,
    },
    {
        "id": "CTRL-ID-002",
        "category": Category.IDENTITY,
        "title": "Privileged Account Protection",
        "short_title": "Admin Accounts",
        "description": "Admin and privileged accounts must be separate from daily-use accounts and protected with strong authentication.",
        "why_it_matters": "Attackers target admin accounts because they control everything. A compromised admin account means total system access.",
        "how_to_fix": [
            "Create dedicated admin accounts separate from regular email accounts.",
            "Never use admin accounts for email or web browsing.",
            "Enable MFA on all admin accounts.",
            "Audit admin accounts quarterly.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-05"], "cis": ["5.4"], "cyber_insurance": True},
        "severity": Severity.CRITICAL,
        "evidence_type": EvidenceType.IDENTITY_PROVIDER,
        "estimated_minutes": 45,
        "weight": 4,
    },
    {
        "id": "CTRL-ID-003",
        "category": Category.IDENTITY,
        "title": "User Access Review",
        "short_title": "Access Review",
        "description": "Regularly review who has access to your systems and remove unnecessary or outdated permissions.",
        "why_it_matters": "Former employees, outdated vendors, and over-privileged accounts are common attack vectors.",
        "how_to_fix": [
            "List all active user accounts in each system.",
            "Remove accounts for employees who have left.",
            "Review and reduce permissions to the minimum needed.",
            "Schedule this review quarterly.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-01"], "cis": ["5.1"], "hipaa": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.IDENTITY_PROVIDER,
        "estimated_minutes": 60,
        "weight": 4,
    },
    {
        "id": "CTRL-ID-004",
        "category": Category.IDENTITY,
        "title": "Password Policy",
        "short_title": "Passwords",
        "description": "Enforce strong, unique passwords across all accounts. Use a password manager.",
        "why_it_matters": "Weak or reused passwords are responsible for a significant portion of breaches.",
        "how_to_fix": [
            "Require passwords of at least 12 characters.",
            "Ban commonly-used passwords.",
            "Recommend or require a business password manager (1Password, Bitwarden).",
            "Do not require frequent mandatory rotations — it leads to weaker passwords.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-02"], "cis": ["5.2"], "ftc": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.IDENTITY_PROVIDER,
        "estimated_minutes": 20,
        "weight": 4,
    },
    {
        "id": "CTRL-ID-005",
        "category": Category.IDENTITY,
        "title": "Account Termination Process",
        "short_title": "Offboarding",
        "description": "Immediately disable or remove access for employees who leave the company.",
        "why_it_matters": "Terminated employees retaining access is a top insider threat risk.",
        "how_to_fix": [
            "Create a written offboarding checklist that includes account termination.",
            "Disable accounts on the day employment ends.",
            "Revoke access to cloud services, email, and any shared accounts.",
            "Transfer data and reassign permissions before disabling.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-01"], "cis": ["5.3"], "hipaa": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 15,
        "weight": 3,
    },
    # ── DEVICES ───────────────────────────────────────────────────────────────
    {
        "id": "CTRL-DEV-001",
        "category": Category.DEVICES,
        "title": "Device Encryption",
        "short_title": "Encryption",
        "description": "Enable full-disk encryption on all computers and laptops used for business.",
        "why_it_matters": "If a laptop is lost or stolen, encryption makes the data unreadable without the password.",
        "how_to_fix": [
            "On Windows: Enable BitLocker via Settings → System → BitLocker.",
            "On Mac: Enable FileVault via System Settings → Privacy & Security → FileVault.",
            "Save recovery keys to a secure location (not the encrypted device).",
            "Verify encryption is active on all business devices.",
        ],
        "frameworks": {"nist_csf": ["PR.DS-01"], "cis": ["3.6"], "hipaa": True, "pci_dss": True},
        "severity": Severity.CRITICAL,
        "evidence_type": EvidenceType.ENDPOINT,
        "estimated_minutes": 15,
        "weight": 5,
    },
    {
        "id": "CTRL-DEV-002",
        "category": Category.DEVICES,
        "title": "Software Updates & Patching",
        "short_title": "Updates",
        "description": "Keep operating systems and applications up to date with security patches.",
        "why_it_matters": "The majority of successful attacks exploit known vulnerabilities that already have patches available.",
        "how_to_fix": [
            "Enable automatic updates on Windows and macOS.",
            "Set updates to install outside business hours.",
            "Verify critical patches within 30 days of release.",
            "Include all business-critical applications, not just the OS.",
        ],
        "frameworks": {"nist_csf": ["PR.PS-02"], "cis": ["7.3"], "ftc": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.ENDPOINT,
        "estimated_minutes": 20,
        "weight": 4,
    },
    {
        "id": "CTRL-DEV-003",
        "category": Category.DEVICES,
        "title": "Endpoint Protection",
        "short_title": "Antivirus / EDR",
        "description": "Install and maintain endpoint protection software on all business devices.",
        "why_it_matters": "Modern endpoint protection detects and blocks malware, ransomware, and phishing attempts before they cause damage.",
        "how_to_fix": [
            "Select a business-grade endpoint protection solution (Microsoft Defender, SentinelOne, CrowdStrike).",
            "Deploy to all business computers, including remote employees.",
            "Ensure real-time protection is enabled.",
            "Review alerts weekly.",
        ],
        "frameworks": {"nist_csf": ["DE.CM-09"], "cis": ["10.1"], "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.ENDPOINT,
        "estimated_minutes": 60,
        "weight": 4,
    },
    {
        "id": "CTRL-DEV-004",
        "category": Category.DEVICES,
        "title": "Screen Lock Policy",
        "short_title": "Screen Lock",
        "description": "All devices must automatically lock after a short period of inactivity.",
        "why_it_matters": "An unlocked workstation in a public space is an open door.",
        "how_to_fix": [
            "Set screen lock timeout to 5–10 minutes on all devices.",
            "Require a password or biometric to unlock.",
            "On Windows: Settings → Accounts → Sign-in options.",
            "On Mac: System Settings → Lock Screen.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-03"], "cis": ["4.3"], "hipaa": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.ENDPOINT,
        "estimated_minutes": 10,
        "weight": 3,
    },
    {
        "id": "CTRL-DEV-005",
        "category": Category.DEVICES,
        "title": "Device Inventory",
        "short_title": "Asset Inventory",
        "description": "Maintain an accurate list of all devices used for business purposes.",
        "why_it_matters": "You cannot protect what you don't know exists.",
        "how_to_fix": [
            "Create a spreadsheet or use a tool to list all business devices.",
            "Include: device name, type, owner, OS version, encryption status.",
            "Update the inventory when devices are added or removed.",
            "Review quarterly.",
        ],
        "frameworks": {"nist_csf": ["ID.AM-01"], "cis": ["1.1"]},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 30,
        "weight": 4,
    },
    # ── DATA ──────────────────────────────────────────────────────────────────
    {
        "id": "CTRL-DATA-001",
        "category": Category.DATA,
        "title": "Data Inventory",
        "short_title": "Data Inventory",
        "description": "Know what sensitive data your business holds and where it lives.",
        "why_it_matters": "You cannot protect data you don't know about.",
        "how_to_fix": [
            "List the types of sensitive data you hold.",
            "Document where each type is stored.",
            "Note who has access to each data category.",
            "Review and update annually.",
        ],
        "frameworks": {"nist_csf": ["ID.AM-05"], "cis": ["3.1"], "hipaa": True, "gdpr": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 45,
        "weight": 4,
    },
    {
        "id": "CTRL-DATA-002",
        "category": Category.DATA,
        "title": "Data Classification",
        "short_title": "Data Labels",
        "description": "Categorize data by sensitivity level so it receives appropriate protection.",
        "why_it_matters": "Not all data needs the same protection. Classification helps focus security resources where they matter most.",
        "how_to_fix": [
            "Define 3 simple tiers: Public, Internal, Confidential.",
            "Classify customer data, financial records, and health info as Confidential.",
            "Set access controls and handling rules per tier.",
            "Train employees on the classification scheme.",
        ],
        "frameworks": {"nist_csf": ["ID.AM-05"], "cis": ["3.2"], "hipaa": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 30,
        "weight": 3,
    },
    {
        "id": "CTRL-DATA-003",
        "category": Category.DATA,
        "title": "Backup Strategy",
        "short_title": "Backups",
        "description": "Maintain regular, tested backups of all critical business data using the 3-2-1 rule.",
        "why_it_matters": "Ransomware and accidental deletion destroy businesses. A good backup strategy is your last line of defense.",
        "how_to_fix": [
            "Follow 3-2-1: 3 copies, 2 different media types, 1 offsite.",
            "Enable automatic daily backups to a cloud service.",
            "Ensure backups are separate from live systems.",
            "Document your backup schedule and retention period.",
        ],
        "frameworks": {"nist_csf": ["PR.DS-11"], "cis": ["11.1"], "cyber_insurance": True},
        "severity": Severity.CRITICAL,
        "evidence_type": EvidenceType.BACKUP_PLATFORM,
        "estimated_minutes": 60,
        "weight": 5,
    },
    {
        "id": "CTRL-DATA-004",
        "category": Category.DATA,
        "title": "Backup Verification",
        "short_title": "Test Restores",
        "description": "Regularly verify that backups can actually be restored.",
        "why_it_matters": "Backup systems fail silently. Many businesses discover their backups were corrupted only when they need them.",
        "how_to_fix": [
            "Schedule a monthly test restore of a sample of data.",
            "Document the test: date, what was restored, result.",
            "Ensure the restoration process is documented.",
            "Test full system restoration at least annually.",
        ],
        "frameworks": {"nist_csf": ["RC.RP-04"], "cis": ["11.3"], "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.BACKUP_PLATFORM,
        "estimated_minutes": 30,
        "weight": 4,
    },
    {
        "id": "CTRL-DATA-005",
        "category": Category.DATA,
        "title": "Data Encryption at Rest",
        "short_title": "Data Encryption",
        "description": "Ensure sensitive data is encrypted when stored.",
        "why_it_matters": "Encrypted data is useless to an attacker who steals it.",
        "how_to_fix": [
            "Enable encryption at rest in your cloud storage.",
            "Use encrypted databases for any customer records.",
            "Avoid storing sensitive data in unencrypted spreadsheets.",
            "Verify your cloud provider's encryption settings.",
        ],
        "frameworks": {"nist_csf": ["PR.DS-01"], "cis": ["3.11"], "hipaa": True, "pci_dss": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.CLOUD_PLATFORM,
        "estimated_minutes": 20,
        "weight": 4,
    },
    # ── NETWORK / CLOUD ───────────────────────────────────────────────────────
    {
        "id": "CTRL-NET-001",
        "category": Category.NETWORK,
        "title": "Secure Configuration Baseline",
        "short_title": "Secure Config",
        "description": "Apply security hardening to cloud services and network devices beyond their default settings.",
        "why_it_matters": "Default configurations are designed for convenience, not security.",
        "how_to_fix": [
            "Enable Microsoft Secure Score or Google Workspace Security Health.",
            "Follow recommended security baselines (CIS Benchmarks).",
            "Disable unused services, ports, and features.",
            "Review configuration quarterly.",
        ],
        "frameworks": {"nist_csf": ["PR.PS-01"], "cis": ["4.1"], "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.CLOUD_PLATFORM,
        "estimated_minutes": 90,
        "weight": 4,
    },
    {
        "id": "CTRL-NET-002",
        "category": Category.NETWORK,
        "title": "Security Logging",
        "short_title": "Audit Logs",
        "description": "Enable logging for critical systems to maintain a record of security-relevant events.",
        "why_it_matters": "Logs are essential for detecting attacks and investigating incidents.",
        "how_to_fix": [
            "Enable audit logging in Microsoft 365 or Google Workspace.",
            "Enable CloudTrail if using AWS, or Activity Logs in Azure.",
            "Retain logs for at least 90 days.",
            "Set alerts for suspicious events.",
        ],
        "frameworks": {"nist_csf": ["DE.CM-01"], "cis": ["8.2"], "hipaa": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.CLOUD_PLATFORM,
        "estimated_minutes": 30,
        "weight": 3,
    },
    {
        "id": "CTRL-NET-003",
        "category": Category.NETWORK,
        "title": "External Exposure Management",
        "short_title": "Attack Surface",
        "description": "Identify and minimize what services and systems are exposed to the internet.",
        "why_it_matters": "Every internet-facing service is a potential entry point for attackers.",
        "how_to_fix": [
            "Scan your external presence.",
            "Close unnecessary open ports and services.",
            "Use a firewall or security group to restrict inbound traffic.",
            "Replace VPNs and RDP with modern zero-trust access solutions.",
        ],
        "frameworks": {"nist_csf": ["ID.RA-01"], "cis": ["12.1"], "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.NETWORK,
        "estimated_minutes": 45,
        "weight": 4,
    },
    {
        "id": "CTRL-NET-004",
        "category": Category.NETWORK,
        "title": "Administrative Access Control",
        "short_title": "Admin Access",
        "description": "Restrict and monitor administrative access to cloud platforms and critical systems.",
        "why_it_matters": "Admin access to cloud platforms is the keys to the kingdom.",
        "how_to_fix": [
            "Apply least-privilege: grant only the permissions needed.",
            "Require MFA for all admin console access.",
            "Review admin accounts quarterly.",
            "Enable alerts for admin actions.",
        ],
        "frameworks": {"nist_csf": ["PR.AA-05"], "cis": ["5.4"], "pci_dss": True},
        "severity": Severity.CRITICAL,
        "evidence_type": EvidenceType.CLOUD_PLATFORM,
        "estimated_minutes": 30,
        "weight": 4,
    },
    {
        "id": "CTRL-NET-005",
        "category": Category.NETWORK,
        "title": "Cloud Security Configuration",
        "short_title": "Cloud Security",
        "description": "Review and harden the security settings in your cloud service accounts.",
        "why_it_matters": "Cloud misconfiguration is the leading cause of data breaches.",
        "how_to_fix": [
            "Review Microsoft Secure Score: admin.microsoft.com → Secure Score.",
            "Review Google Workspace Security Dashboard.",
            "Act on the highest-impact recommendations first.",
            "Aim for a score above 70% and review monthly.",
        ],
        "frameworks": {"nist_csf": ["PR.PS-01"], "cis": ["4.2"], "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.CLOUD_PLATFORM,
        "estimated_minutes": 60,
        "weight": 5,
    },
    # ── ORGANIZATION ──────────────────────────────────────────────────────────
    {
        "id": "CTRL-ORG-001",
        "category": Category.ORGANIZATION,
        "title": "Security Policy",
        "short_title": "Security Policy",
        "description": "Maintain a written security policy that documents your security requirements and employee responsibilities.",
        "why_it_matters": "A written policy is required by most insurance carriers and frameworks.",
        "how_to_fix": [
            "Create a 1-2 page Acceptable Use Policy.",
            "Have employees acknowledge the policy in writing annually.",
            "Update the policy when you adopt new technology.",
            "SecurityOS can generate a starter policy for your business.",
        ],
        "frameworks": {"nist_csf": ["GV.PO-01"], "cis": ["17.1"], "hipaa": True, "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 90,
        "weight": 4,
    },
    {
        "id": "CTRL-ORG-002",
        "category": Category.ORGANIZATION,
        "title": "Incident Response Plan",
        "short_title": "Incident Response",
        "description": "Have a documented plan for what to do when a security incident occurs.",
        "why_it_matters": "When an incident happens, panic costs time and money. A plan turns chaos into a structured response.",
        "how_to_fix": [
            "Define what counts as a security incident.",
            "Document who to call (IT provider, cyber insurance, legal).",
            "Define steps: Contain → Investigate → Notify → Recover.",
            "Test the plan with a tabletop exercise annually.",
        ],
        "frameworks": {"nist_csf": ["RS.MA-01"], "cis": ["17.3"], "hipaa": True, "cyber_insurance": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 120,
        "weight": 4,
    },
    {
        "id": "CTRL-ORG-003",
        "category": Category.ORGANIZATION,
        "title": "Employee Security Training",
        "short_title": "Security Training",
        "description": "Train employees on security basics, with a focus on phishing and social engineering.",
        "why_it_matters": "Human error causes 74% of breaches. Training dramatically reduces click rates on phishing emails.",
        "how_to_fix": [
            "Conduct annual security awareness training for all employees.",
            "Run quarterly phishing simulations.",
            "Cover: phishing, password hygiene, device security, social engineering.",
            "Document training completion for compliance records.",
        ],
        "frameworks": {"nist_csf": ["PR.AT-01"], "cis": ["14.1"], "hipaa": True, "ftc": True},
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 60,
        "weight": 4,
    },
    {
        "id": "CTRL-ORG-004",
        "category": Category.ORGANIZATION,
        "title": "Vendor Security Assessment",
        "short_title": "Vendor Security",
        "description": "Assess the security posture of vendors and third parties who have access to your data or systems.",
        "why_it_matters": "Your security is only as strong as your vendors'.",
        "how_to_fix": [
            "List all vendors with access to your data or systems.",
            "Request security certifications (SOC 2, ISO 27001) from critical vendors.",
            "Include security requirements in vendor contracts.",
            "Review high-risk vendors annually.",
        ],
        "frameworks": {"nist_csf": ["GV.SC-06"], "cis": ["15.1"], "hipaa": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 45,
        "weight": 3,
    },
    {
        "id": "CTRL-ORG-005",
        "category": Category.ORGANIZATION,
        "title": "Annual Security Review",
        "short_title": "Security Review",
        "description": "Conduct a comprehensive annual review of your security posture, risks, and controls.",
        "why_it_matters": "Security is not a one-time event. Annual reviews ensure your controls keep pace with your business.",
        "how_to_fix": [
            "Review and update your data inventory and risk assessment.",
            "Test backup restoration.",
            "Review user access and admin accounts.",
            "Update policies and retrain employees.",
            "SecurityOS can generate your annual report automatically.",
        ],
        "frameworks": {"nist_csf": ["GV.RM-01"], "cis": ["17.2"], "hipaa": True, "cyber_insurance": True},
        "severity": Severity.MEDIUM,
        "evidence_type": EvidenceType.POLICY,
        "estimated_minutes": 180,
        "weight": 4,
    },
]

CONTROLS_BY_ID: Dict[str, Dict] = {c["id"]: c for c in CONTROLS}
CONTROLS_BY_CATEGORY: Dict[Category, List[Dict]] = {}
for control in CONTROLS:
    cat = control["category"]
    CONTROLS_BY_CATEGORY.setdefault(cat, []).append(control)
