"""
Okta IAM MCP Server

Exposes read-only tools over the Okta API using each client's own
self-service API token (never a platform-wide credential).

Tools
-----
okta_list_users            List active users with basic profile data
okta_get_user_count        Count of active / inactive / all users
okta_list_groups           List groups and their member counts
okta_list_apps             List configured applications
okta_get_user_app_access   Which apps a user is assigned to
okta_inactive_users        Users who haven't logged in for N days
okta_mfa_adoption          MFA enrollment statistics

All tools are readOnlyHint=True — this MCP server never writes to Okta.

Usage (standalone MCP server, called by the AI agent layer)
-----------------------------------------------------------
  python -m backend.mcp.okta_iam --domain <tenant>.okta.com --token <api_token>

Or, called via the platform's credential lookup:
  from backend.mcp.okta_iam import OktaIAMClient
  client = OktaIAMClient(domain="acme.okta.com", token=decrypted_token)
  users = client.list_users(limit=50)

Integration with Trust Score
-----------------------------
When an Okta credential is stored for a user, _ai_protection_score() in
routes/trust.py will call okta_get_user_count() and okta_mfa_adoption()
to populate real values for the AI & ML Protection pillar instead of
relying on manually-entered control statuses.
"""

import json
import logging
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ─── Low-level Okta API client ────────────────────────────────────────────────

class OktaIAMClient:
    """
    Thin HTTP wrapper around the Okta REST API.
    All calls use read-only endpoints (GET only).
    """

    def __init__(self, domain: str, token: str):
        """
        domain : your Okta organisation domain, e.g. 'acme.okta.com'
        token  : a read-only Okta API token generated by the client from
                 their own Okta admin console (not a shared platform credential)
        """
        self.base = f"https://{domain.rstrip('/')}/api/v1"
        self.headers = {
            "Authorization": f"SSWS {token}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _get(self, path: str, params: Optional[Dict[str, Any]] = None) -> Any:
        url = f"{self.base}{path}"
        if params:
            qs = "&".join(f"{k}={urllib.request.quote(str(v))}" for k, v in params.items() if v is not None)
            url = f"{url}?{qs}"
        req = urllib.request.Request(url, headers=self.headers, method="GET")
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"Okta API error {e.code}: {body}") from e

    # ── Tool implementations ──────────────────────────────────────────────────

    def list_users(self, limit: int = 100, status: str = "ACTIVE") -> List[Dict]:
        """
        readOnlyHint: true
        Returns a list of Okta users with login, name, status, and last_login.
        """
        raw = self._get("/users", params={"limit": min(limit, 200), "filter": f'status eq "{status}"'})
        return [
            {
                "id":         u.get("id"),
                "login":      u.get("profile", {}).get("login"),
                "first_name": u.get("profile", {}).get("firstName"),
                "last_name":  u.get("profile", {}).get("lastName"),
                "status":     u.get("status"),
                "last_login": u.get("lastLogin"),
                "created":    u.get("created"),
            }
            for u in (raw if isinstance(raw, list) else [])
        ]

    def get_user_count(self) -> Dict[str, int]:
        """
        readOnlyHint: true
        Returns counts of ACTIVE, DEPROVISIONED, SUSPENDED, and LOCKED_OUT users.
        """
        counts: Dict[str, int] = {}
        for status in ("ACTIVE", "DEPROVISIONED", "SUSPENDED", "LOCKED_OUT"):
            try:
                rows = self._get("/users", params={"limit": 1, "filter": f'status eq "{status}"'})
                # Okta doesn't return total count in body; pagination link gives it
                # We use limit=1 just to confirm existence; for accurate counts
                # the caller should paginate — here we return at-least-1 or 0.
                counts[status.lower()] = len(rows) if isinstance(rows, list) else 0
            except Exception:
                counts[status.lower()] = -1  # unavailable
        return counts

    def list_groups(self, limit: int = 50) -> List[Dict]:
        """readOnlyHint: true — list Okta groups with member counts."""
        raw = self._get("/groups", params={"limit": min(limit, 200)})
        return [
            {
                "id":           g.get("id"),
                "name":         g.get("profile", {}).get("name"),
                "description":  g.get("profile", {}).get("description"),
                "member_count": g.get("objectClass"),  # actual count requires separate call
            }
            for g in (raw if isinstance(raw, list) else [])
        ]

    def list_apps(self, limit: int = 50) -> List[Dict]:
        """readOnlyHint: true — list configured Okta applications."""
        raw = self._get("/apps", params={"limit": min(limit, 200)})
        return [
            {
                "id":       a.get("id"),
                "name":     a.get("name"),
                "label":    a.get("label"),
                "status":   a.get("status"),
                "sign_on":  a.get("signOnMode"),
                "created":  a.get("created"),
            }
            for a in (raw if isinstance(raw, list) else [])
        ]

    def get_user_app_access(self, user_id: str) -> List[Dict]:
        """readOnlyHint: true — which apps a given user is assigned to."""
        raw = self._get(f"/users/{user_id}/appLinks")
        return [
            {
                "app_name":  a.get("appName"),
                "app_id":    a.get("appInstanceId"),
                "label":     a.get("label"),
                "login_url": a.get("loginUrl"),
            }
            for a in (raw if isinstance(raw, list) else [])
        ]

    def inactive_users(self, days: int = 90, limit: int = 50) -> List[Dict]:
        """
        readOnlyHint: true
        Users whose last login is older than `days` days (or who have never logged in).
        """
        from datetime import datetime, timedelta
        cutoff = (datetime.utcnow() - timedelta(days=days)).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        raw = self._get(
            "/users",
            params={
                "filter": f'lastLogin lt "{cutoff}" and status eq "ACTIVE"',
                "limit": min(limit, 200),
            },
        )
        return [
            {
                "login":      u.get("profile", {}).get("login"),
                "last_login": u.get("lastLogin"),
                "status":     u.get("status"),
            }
            for u in (raw if isinstance(raw, list) else [])
        ]

    def mfa_adoption(self) -> Dict[str, Any]:
        """
        readOnlyHint: true
        Summarises MFA factor enrollment across the org.
        Returns enrolled count, factor types in use.
        """
        factors_raw = self._get("/users", params={"limit": 200, "filter": 'status eq "ACTIVE"'})
        users = factors_raw if isinstance(factors_raw, list) else []
        enrolled = 0
        factor_types: Dict[str, int] = {}
        for user in users:
            uid = user.get("id")
            if not uid:
                continue
            try:
                factors = self._get(f"/users/{uid}/factors")
                if factors:
                    enrolled += 1
                    for f in factors:
                        ft = f.get("factorType", "unknown")
                        factor_types[ft] = factor_types.get(ft, 0) + 1
            except Exception:
                pass  # skip users where we can't fetch factors
        return {
            "total_active_users":   len(users),
            "mfa_enrolled":         enrolled,
            "mfa_adoption_pct":     round(enrolled / len(users) * 100, 1) if users else 0,
            "factor_types":         factor_types,
        }


# ─── Verification helper (used by credentials.py verify endpoint) ─────────────

def verify_okta_token(token: str, domain: Optional[str] = None) -> Tuple[bool, str]:
    """
    Quick check: try to GET /api/v1/users?limit=1 with the supplied token.
    Returns (ok: bool, message: str).
    """
    if not domain:
        # Token might be in format  "domain::token"  if stored that way
        if "::" in token:
            domain, token = token.split("::", 1)
        else:
            return False, "Cannot verify: domain unknown. Store credential as 'domain::token'."
    try:
        client = OktaIAMClient(domain=domain, token=token)
        client._get("/users", params={"limit": 1})
        return True, f"Okta credential verified against {domain}"
    except RuntimeError as e:
        return False, str(e)
    except Exception as e:
        return False, f"Network error: {e}"


# ─── MCP tool registry (used by the AI agent layer) ──────────────────────────

MCP_TOOLS = [
    {
        "name":         "okta_list_users",
        "description":  "List Okta users. Returns login, name, status, last_login. Read-only.",
        "readOnlyHint": True,
        "inputSchema": {
            "type": "object",
            "properties": {
                "limit":  {"type": "integer", "default": 50, "description": "Max users to return (max 200)"},
                "status": {"type": "string",  "default": "ACTIVE", "enum": ["ACTIVE","DEPROVISIONED","SUSPENDED"]},
            },
        },
    },
    {
        "name":         "okta_get_user_count",
        "description":  "Get counts of Okta users by status (ACTIVE, DEPROVISIONED, SUSPENDED, LOCKED_OUT). Read-only.",
        "readOnlyHint": True,
        "inputSchema":  {"type": "object", "properties": {}},
    },
    {
        "name":         "okta_list_groups",
        "description":  "List Okta groups with names and descriptions. Read-only.",
        "readOnlyHint": True,
        "inputSchema": {
            "type": "object",
            "properties": {"limit": {"type": "integer", "default": 50}},
        },
    },
    {
        "name":         "okta_list_apps",
        "description":  "List configured Okta applications (label, sign-on mode, status). Read-only.",
        "readOnlyHint": True,
        "inputSchema": {
            "type": "object",
            "properties": {"limit": {"type": "integer", "default": 50}},
        },
    },
    {
        "name":         "okta_inactive_users",
        "description":  "Return ACTIVE users who have not logged in for at least N days. Read-only.",
        "readOnlyHint": True,
        "inputSchema": {
            "type": "object",
            "properties": {
                "days":  {"type": "integer", "default": 90, "description": "Inactivity threshold in days"},
                "limit": {"type": "integer", "default": 50},
            },
        },
    },
    {
        "name":         "okta_mfa_adoption",
        "description":  "Summarise MFA factor enrollment across the Okta org. Read-only.",
        "readOnlyHint": True,
        "inputSchema":  {"type": "object", "properties": {}},
    },
]


def call_tool(tool_name: str, args: Dict[str, Any], client: OktaIAMClient) -> Any:
    """Dispatch an MCP tool call to the correct OktaIAMClient method."""
    dispatch = {
        "okta_list_users":       lambda: client.list_users(**args),
        "okta_get_user_count":   lambda: client.get_user_count(),
        "okta_list_groups":      lambda: client.list_groups(**args),
        "okta_list_apps":        lambda: client.list_apps(**args),
        "okta_get_user_app_access": lambda: client.get_user_app_access(args["user_id"]),
        "okta_inactive_users":   lambda: client.inactive_users(**args),
        "okta_mfa_adoption":     lambda: client.mfa_adoption(),
    }
    fn = dispatch.get(tool_name)
    if fn is None:
        raise ValueError(f"Unknown tool: {tool_name}")
    return fn()


# ─── Standalone MCP server entry point ───────────────────────────────────────

if __name__ == "__main__":
    import argparse, sys

    parser = argparse.ArgumentParser(description="Okta IAM MCP Server")
    parser.add_argument("--domain", required=True, help="Okta domain, e.g. acme.okta.com")
    parser.add_argument("--token",  required=True, help="Read-only Okta API token")
    args = parser.parse_args()

    client = OktaIAMClient(domain=args.domain, token=args.token)

    # Simple stdio JSON-RPC loop (compatible with MCP Inspector)
    print(json.dumps({"jsonrpc": "2.0", "method": "tools/list", "result": {"tools": MCP_TOOLS}}))
    sys.stdout.flush()

    for line in sys.stdin:
        try:
            req = json.loads(line)
            tool = req.get("params", {}).get("name")
            tool_args = req.get("params", {}).get("arguments", {})
            result = call_tool(tool, tool_args, client)
            print(json.dumps({"jsonrpc": "2.0", "id": req.get("id"), "result": {"content": [{"type": "text", "text": json.dumps(result)}]}}))
        except Exception as e:
            print(json.dumps({"jsonrpc": "2.0", "id": None, "error": {"code": -32000, "message": str(e)}}))
        sys.stdout.flush()


# ─── Violation-enriched tools ────────────────────────────────────────────────
# These return structured records ready for POST /api/violations/ingest,
# with entity identity (email, display_name) and control mapping.

CONTROL_MAPPINGS = {
    "inactive_mfa": {
        "control_id":     "AC-17",   # Remote Access / MFA
        "violation_type": "inactive_mfa",
        "entity_type":    "user",
    },
    "stale_access": {
        "control_id":     "AC-2",    # Account Management
        "violation_type": "stale_access",
        "entity_type":    "user",
    },
    "no_mfa_enrolled": {
        "control_id":     "IA-3",    # Device Identification
        "violation_type": "no_mfa_enrolled",
        "entity_type":    "user",
    },
    "privileged_user_no_review": {
        "control_id":     "AC-6",    # Least Privilege
        "violation_type": "privileged_user_no_review",
        "entity_type":    "user",
    },
}


def okta_get_violation_sources(
    client: "OktaIAMClient",
    inactive_days: int = 90,
) -> list:
    """
    readOnlyHint: true.

    Returns a list of violation records ready for /api/violations/ingest,
    including the specific user email and display name for each finding.

    Violation types detected:
      • stale_access        — active users inactive for >inactive_days days
      • no_mfa_enrolled     — active users with no MFA factors enrolled
    """
    import logging
    log = logging.getLogger(__name__)
    results = []

    # 1. Stale access — active users who haven't logged in for N days
    try:
        stale = client.inactive_users(days=inactive_days, limit=200)
        for u in stale:
            results.append({
                "control_id":    CONTROL_MAPPINGS["stale_access"]["control_id"],
                "violation_type": "stale_access",
                "source_vendor": "okta",
                "entity_type":   "user",
                "source_id":     u.get("id") or u.get("login"),
                "email":         u.get("login"),
                "display_name":  f"{u.get('first_name', '')} {u.get('last_name', '')}".strip() or u.get("login"),
                "raw_context": {
                    "last_login":      u.get("last_login"),
                    "inactive_days":   inactive_days,
                    "okta_status":     u.get("status"),
                },
            })
    except Exception as e:
        log.warning("okta stale_access fetch failed: %s", e)

    # 2. No MFA enrolled — active users without any enrolled factor
    try:
        active_users = client.list_users(limit=200, status="ACTIVE")
        for u in active_users:
            uid = u.get("id") or u.get("source_id")
            if not uid:
                continue
            try:
                factors = client._get(f"/users/{uid}/factors")
                if not factors:  # empty list = no MFA
                    results.append({
                        "control_id":     CONTROL_MAPPINGS["no_mfa_enrolled"]["control_id"],
                        "violation_type": "no_mfa_enrolled",
                        "source_vendor":  "okta",
                        "entity_type":    "user",
                        "source_id":      uid,
                        "email":          u.get("login"),
                        "display_name":   u.get("login"),
                        "raw_context": {"okta_status": "ACTIVE", "factors": []},
                    })
            except Exception:
                pass  # skip individual user fetch errors
    except Exception as e:
        log.warning("okta no_mfa_enrolled fetch failed: %s", e)

    return results
